version: '2'

services:
  api:
    build: .
    command: >
      gunicorn -b 0.0.0.0:8000
      --access-logfile -
      --reload
      "todo_api.app:create_app()"
    environment:
      PYTHONUNBUFFERED: 'true'
    volumes:
    - './todo_api'
    ports:
    - '8000:80'
