version: '2'

services:
  db:
    image: postgres:12.1-alpine
    restart: always
    hostname: db
    volumes:
    - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: todo_api
      POSTGRES_PASSWORD: P@ssw0rd
      POSTGRES_DB: todo_api
    ports:
    - '5432:5432'
  api:
    build: .
    command: >
      gunicorn -b 0.0.0.0:8000
      --access-logfile -
      --reload
      "todo_api.app:create_app()"
    environment:
      PYTHONUNBUFFERED: 'true'
    volumes:
    - './todo_api'
    ports:
    - '8000:8000'
volumes:
  postgres_data: